import type { ReactElement } from 'react';
import React from 'react';
import Head from 'next/head';
import { Toaster } from 'react-hot-toast';
import Script from 'next/script';
import { Provider } from 'react-redux';
import { store } from '../store';
import Header from '../components/header';

function Layout({ children }: { children: ReactElement }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Provider store={store}>
                <Header />
                <main>{children}</main>
                <Toaster />
            </Provider>
            <footer>
                <div className="py-4">
                    <div className="container text-center">
                        <a
                            href="https://github.com/sergeevpasha/trion"
                            className="badge pl-2"
                            target="_blank"
                            rel="noreferrer"
                        >
                            <div className="name">
                                <span>Build</span>
                            </div>
                            <div className="status blue">
                                <span>v0.1.0</span>
                            </div>
                        </a>
                    </div>
                </div>
            </footer>
            <Script src="https://www.googletagmanager.com/gtag/js?id=G-TLM2DQ1DXQ" strategy="afterInteractive" />
            <Script id="google-analytics" strategy="afterInteractive">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', 'G-TLM2DQ1DXQ');
                `}
            </Script>
            <Script id="yandex-counter" strategy="afterInteractive">
                {`
                    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                    m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
                    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
                    
                    ym(89109733, "init", {
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                    });
                `}
            </Script>
        </>
    );
}

export default Layout;
