import type { ReactElement } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Button } from 'react-bootstrap';
import React, { useState } from 'react';
import { Toaster } from 'react-hot-toast';
import Script from 'next/script';
import AddDataModal from '../components/addDataModal';

function Layout({ children }: { children: ReactElement }) {
    const [modalShow, setModalShow] = useState(false);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div className="container d-flex justify-content-between">
                    <div className="header-logo">
                        <Image src="/images/logo.png" width="32" height="32" />
                        <h1>
                            Fitmint<span>.guide</span>
                        </h1>
                    </div>
                    <Button className="primary" onClick={() => setModalShow(true)}>
                        Post run results
                    </Button>
                </div>
            </header>
            <main>{children}</main>
            <AddDataModal show={modalShow} onHide={() => setModalShow(false)} />
            <Toaster />
            <Script src="https://www.googletagmanager.com/gtag/js?id=G-TLM2DQ1DXQ" strategy="afterInteractive" />
            <Script id="google-analytics" strategy="afterInteractive">
                {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', 'G-TLM2DQ1DXQ');
                `}
            </Script>
            <Script id="yandex-counter" strategy="afterInteractive">
                {`
                    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                    m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
                    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
                    
                    ym(89109733, "init", {
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true
                    });
                `}
            </Script>
        </>
    );
}

export default Layout;
